# -*- coding: utf-8 -*-
"""Udemy C1_14012024.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1NPBnwOR-km-kMt7aZmOWoS6Rh9Yky1ct
"""

import pandas as pd
import io
import matplotlib.pyplot as plt
from sklearn import linear_model
import numpy as np
from sklearn import linear_model
from google.colab import drive
drive.mount('/content/drive')
df = pd.read_csv('/content/drive/MyDrive/h.csv')
df.head()

# Commented out IPython magic to ensure Python compatibility.
# %matplotlib inline
plt.xlabel("Area")
plt.ylabel("Price")
plt.title("House Price Perdiction")
plt.scatter(df["Area"], df["Price"])

Area=df.drop('Price', axis = 'columns')
Area

Price=df.Price
Price

reg =linear_model.LinearRegression()
reg.fit(Area, Price)